apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  name: ros2-cs9-container-build
spec:
  pipelineRef:
    name: container-build
  params:
    - name: SCM_URL
      value: "https://gitlab.com/fedora/sigs/robotics/images/ros2-cs9.git"
    - name: SCM_REFS
      value: "main"
    - name: RUNNER_IMAGE
      value: "quay.io/lrossett/tekton-runner:latest"
    - name: IMAGE_NAME
      value: "ros-cs9:latest"
  workspaces:
    - name: shared-data
      persistentVolumeClaim:
        claimName: task-1
  taskRunSpecs: {}
  taskRunTemplate:
    podTemplate: {}

